kuka_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  left_gripper_finger_joint_controller:
    type: effort_controllers/JointPositionController
    joint: left_gripper_finger_joint
    pid: {p: 1000.0, i: 200, d: 10.0}
  right_gripper_finger_joint_controller:
    type: effort_controllers/JointPositionController
    joint: right_gripper_finger_joint
    pid: {p: 1000.0, i: 200, d: 10.0}

  joint1_arm_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 1800.0, i: 1000, d: 100.0}
  
  joint2_arm_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 3000.0, i: 200, d: 60.0}
  
  joint3_arm_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1800.0, i: 100, d: 10.0}
  
  joint4_arm_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1000.0, i: 200, d: 10.0}
  
  joint5_arm_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 1000.0, i: 200, d: 10.0}

  joint6_arm_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 1000.0, i: 200, d: 10.0}
